=== HagerHussien/php-xml/data.dtd
<!ELEMENT users (user+)>
<!ELEMENT user (name, gender, phone, email)>
<!ATTLIST user   id CDATA #REQUIRED >
<!ELEMENT name (#PCDATA)>
<!ELEMENT gender (male|female) #IMPLIED>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== HagerHussien/php-xml/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "data.dtd">
<users>
<user id="58b1d84fcd188"><name>hager</name><gender>female</gender><phone>5050550</phone><email>hager@gmail.com</email></user><user id="58b1ead98e24f"><name>ali</name><gender>male</gender><phone>202020000</phone><email>ali@gmail.com</email></user><user id="58b69a9a65ad1"><name>noha salah</name><gender>FEMALE</gender><phone>12345678</phone><email>koko@yahoo.com</email></user></users>
